import {
    Utensils,
    Car,
    ShoppingBag,
    Clapperboard,
    Receipt,
    HeartPulse,
    Building2,
    Home,
    Soup,
    ShoppingCart,
    Coffee,
    Tags,
    TramFront,
    Fuel,
    Plane,
    Shirt,
    Cpu,
    ShoppingBasket,
    Wine,
    CupSoda,
    Sandwich,
    Wrench,
    Flame,
    Wifi,
    GlassWater,
    Dumbbell,
    Gamepad2,
    Luggage,
    Stethoscope,
    ShieldCheck,
    BookOpen,
    GraduationCap,
    School,
    Gift,
    PartyPopper,
    PawPrint,
    BadgeDollarSign,
    Medal,
    Briefcase,
    PiggyBank,
    RotateCcw,
    Sparkles,
    Lamp,
    HandCoins,
    HandHeart,
    AlertCircle,
    HelpCircle,
    Bike,
    Wallet,
} from "lucide-react"
import type { LucideIcon } from "lucide-react"

export const categoryIconMap: Record<string, LucideIcon> = {
    utensils: Utensils,
    car: Car,
    "shopping-bag": ShoppingBag,
    clapperboard: Clapperboard,
    receipt: Receipt,
    "heart-pulse": HeartPulse,
    rent: Home,
    bills: Receipt,
    office: Building2,
    groceries: ShoppingCart,
    coffee: Coffee,
    soup: Soup,
    "tram-front": TramFront,
    fuel: Fuel,
    plane: Plane,
    shirt: Shirt,
    cpu: Cpu,
    "shopping-basket": ShoppingBasket,
    wine: Wine,
    "cup-soda": CupSoda,
    sandwich: Sandwich,
    wrench: Wrench,
    flame: Flame,
    wifi: Wifi,
    "glass-water": GlassWater,
    dumbbell: Dumbbell,
    "gamepad-2": Gamepad2,
    luggage: Luggage,
    stethoscope: Stethoscope,
    "shield-check": ShieldCheck,
    "book-open": BookOpen,
    "graduation-cap": GraduationCap,
    school: School,
    gift: Gift,
    "party-popper": PartyPopper,
    paw: PawPrint,
    "paw-print": PawPrint,
    "badge-dollar-sign": BadgeDollarSign,
    medal: Medal,
    briefcase: Briefcase,
    "piggy-bank": PiggyBank,
    "rotate-ccw": RotateCcw,
    sparkles: Sparkles,
    lamp: Lamp,
    "hand-coins": HandCoins,
    "hand-heart": HandHeart,
    "alert-circle": AlertCircle,
    "help-circle": HelpCircle,
    bike: Bike,
    wallet: Wallet,
}

export const defaultCategoryIcon = Tags

export function getCategoryIcon(icon?: string): LucideIcon {
    if (!icon) return Tags
    const key = icon.toLowerCase()
    return categoryIconMap[key] || Tags
}
